---
title: "Housing Sales Analysis for Staten Island borough"
author: "Johnny Quick, Olufemi Adesanya, and Celia Taylor"
date: "June 1, 2016"
output: 
  html_document:
    keep_md: true
---

# Analysis of gross square feet to sales price

## Session Info
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] htmltools_0.3.5 tools_3.3.0     yaml_2.1.13     Rcpp_0.12.4     rmarkdown_0.9.6
[6] digest_0.6.9   

# Code process

The following code calls the Main.R script which sets environment variables,
ensures packages are loaded that are needed, and then calls 3 R scripts:
LoadData.R, CleanData.R, and AnalyzeData.R

LoadData.R reads an Excel file for Staten Island Sales

LoadData.R will also produce the following output:  
  * Header of bk dataset  
  * 5-number summary of bk dataset  
  * Structure of bk dataset  

CleanData.R does the following:  
  * Cleans up sales price and makes it numeric  
  * Makes all variable names lower case  
  * Gets rid of leading digits for gross square feet and land  
  * Changes sales date to R's date format  
  * Subsets year from the sales date into a variable  
  * Removes homes with sales prices of 0  
  * Removes homes with sales prices that don't seem like actual sales  
  
CleandData.R will also produce the following graphics and output:  
  * Histogram of sale.price.n which shows us something is off here  
  * Histogram of sale.price.n for sales prices greater than 0  
  * Histogram of gross.sqft [sale.price.n==0]  
  * Plot gross.sqft related to sale.price.n  
  * Plot log(gross.sqft) related to log(sale.price.n)  
  * Check dimensions of bk.homes dataset which is 1-, 2-, and 3- family homes  
  * Plot log(gross.sqft) related to log(sale.price.n)  
  * 5-number summary of bk.homes dataset for homes with sale.price.n < 100,000  

AnalyzeData.R does a plot of gross square feet related to sales price  

```{r mainchunk}
maind <- "/Users/Johnny/OneDrive/Documents/6306/Unit3/StatenIslandRepo"
setwd(maind)
source("Main.R")
```

As you can see from the plot above, there is a positive linear relation between gross square feet and sales price for housing in the Staten Island borough
